# Change database name, then run "rake db:create db:migrate"

defaults: &defaults
  encoding: utf-8
  username: splendid
  password:
  pool: 5
  host: 127.0.0.1
  reconnect: true
  adapter: postgresql

development:
  <<: *defaults
  database: myapp_dev

test: &test
  <<: *defaults
  database: myapp_test

cucumber:
  <<: *test